baseurl: ""
url: "https://friedenauplastikfrei.github.io"

title: "Friedenau Plastikfrei"
description: "Webauftritt der Nachbarschaftsinitiative Friedenau Plastikfrei"
avatar: "assets/img/logo.svg"
favicon: "assets/favicon.ico"

header_text: '<img alt="logo" src="/assets/img/logo.svg">'
header_feature_image: "assets/img/garbage.jpg"
header_feature_image_responsive: true
footer_text: '<a href="/impressum">Impressum</a>, <a href="/datenschutz">Datenschutzerkl√§rung</a>, <a href="/attribution">Attribution</a>, <a href="/kontakte">Kontakte</a>'

future: true
excerpt: true
post_navigation: true

collections:
  blog:
    output: true
  events:
    output: true
    permalink: /veranstaltungen/:name
  recommendations:
    output: true
    permalink: /empfehlungen/:name

remote_theme: sylhare/Type-on-Strap
